name: Scheduled Index.html Update and Deploy
on:
  schedule:
    - cron: '0 15 25 7 *' # Runs on July 25th at 11:00 AM EDT
  workflow_dispatch: # Allows manual triggering for testing
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Checkout staging branch to get index.html
        uses: actions/checkout@v4
        with:
          ref: staging
          path: staging
      - name: Check deployment date
        run: |
          if [ "$(date +%Y-%m-%d)" != "2025-07-25" ]; then
            echo "Not the scheduled date, exiting"
            exit 0
          fi
      - name: Copy index.html from staging to main
        run: |
          cp staging/index.html .
          rm -rf staging
      - name: Commit changes to main
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add index.html
          git commit -m "Update index.html from staging on 2025-07-25"
          git push origin main
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
